export const constantStorage = {
  USER_AUTH: "USER_AUTH",
  CURRENT_ACTIVE_STEP: "CURRENT_ACTIVE_STEP",
  LOCAL_ACCOMMODATION_QUOTES: "LOCAL_ACCOMMODATION_QUOTES",
  SIDEBAR_VISIBLE: "SIDEBAR_VISIBLE",
  INDIRECT_COSTS_PERCENTAGE: "INDIRECT_COSTS_PERCENTAGE",
  ITINERARY_DAYS_NUMBER: "ITINERARY_DAYS_NUMBER",
  ITINERARY_INITIAL_DATE: "ITINERARY_INITIAL_DATE",
  ITINERARY_CURRENT_SELECTED_DAY: "ITINERARY_CURRENT_SELECTED_DAY",
  ITINERARY_CURRENT_ACTIVITY: "ITINERARY_CURRENT_ACTIVITY",
};
